### PR TITLE
Update TurkishSFW.xml

### PR DESCRIPTION
**Pull request by Halfcelse7**

### CODE REVIEW

**Review by Halfcelse7 — COMMENTED** [review]
Made some addition

**Review by Halfcelse7 — COMMENTED** [review]
made some addition

**Review by Halfcelse7 — COMMENTED** [review]
made some addition

**Review by Halfcelse7 — COMMENTED** [review]
made some addition

**Review by Halfcelse7 — COMMENTED** [review]
made some addition

**Review by tmogeid — APPROVED** [review]

**Pull request merged**
